#!/bin/bash
# Modified from http://linuxcommand.org/lc3_adv_dialog.php
# while-menu-dialog: a menu driven system information program


DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=25
#changed width of box to accomodate message options
WIDTH=50 

display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "Operating systems assignment 2" \
    --title "Menu" \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 10 \
    "1" "Show Sys Inf" \
    "2" "Storage Inf" \
    "3" "Utilization" \
    "4" "Graphic File Display"\
    "5" "File List"\
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    0 )
      clear
      echo "Program terminated."
      ;;
    1 )
      result=$(echo "Hostname: $HOSTNAME"; uptime)
      display_result "System Information"
      ;;
    2 )
      result=$(df -h)
      display_result "Disk Space"
      ;;
    3 )
      if [[ $(id -u) -eq 0 ]]; then
        result=$(du -sh /home/* 2> /dev/null)
        display_result "Home Space Utilization (All Users)"
      else
        result=$(du -sh $HOME 2> /dev/null)
        display_result "Home Space Utilization ($USER)"
      fi
      ;;
	4 )
DIALOG=${DIALOG=dialog}
	FILE=`$DIALOG --stdout --title "Please choose a file" --fselect $HOME/ 14 48`

case $? in
	0)
		echo "\"$FILE\" chosen" 
		cd $FILE	;;
	1)
		echo "Cancel pressed.";;
	255)
		echo "Box closed.";;
esac
;;
5)
	result=$(ls -d -s5)
	display_result "file list"

;;
  esac
done
